# Generated by Django 5.2.14 on 2026-05-25 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_unique_active_deep_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperReadingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_status', models.CharField(choices=[('unread', 'Unread'), ('skimmed', 'Skimmed'), ('deep_reading', 'Deep reading'), ('discussed', 'Discussed'), ('adopted', 'Adopted'), ('rejected', 'Rejected')], default='unread', max_length=32)),
                ('reproduction_status', models.CharField(choices=[('unknown', 'Unknown'), ('not_applicable', 'Not applicable'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('reproduced', 'Reproduced'), ('failed', 'Failed')], default='unknown', max_length=32)),
                ('next_step', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_paper_reading_states', to=settings.AUTH_USER_MODEL)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_state', to='papers.paper')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_paper_reading_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'paper_id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('light', 'Light'), ('deep', 'Deep')], max_length=16)),
                ('profile_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='needs_review', max_length=24)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_reviews', to='papers.paper')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_reading_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['paper', 'profile_type', 'profile_id'], name='papers_read_paper_i_910644_idx'), models.Index(fields=['status'], name='papers_read_status_9e0f6c_idx')],
            },
        ),
    ]
