# Generated by Django 5.2.14 on 2026-05-25 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('mode', models.CharField(choices=[('compare', 'Compare'), ('reproduction_checklist', 'Reproduction checklist'), ('literature_brief', 'Literature brief'), ('freeform_scoped', 'Freeform scoped')], default='freeform_scoped', max_length=40)),
                ('scope_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssistantExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('context_warning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='assistant.assistantsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
