# Generated by Django 5.2.14 on 2026-05-25 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_taskrecord_result_object'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.PositiveBigIntegerField()),
                ('dimension', models.CharField(choices=[('metadata', 'Metadata'), ('ai_output', 'AI output'), ('reproduction', 'Reproduction'), ('document', 'Document'), ('search_index', 'Search index')], max_length=40)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=24)),
                ('score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('evidence_json', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_issues', to='tasks.taskrecord')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='quality_qua_object__725361_idx'), models.Index(fields=['status', 'severity'], name='quality_qua_status_b450e7_idx')],
            },
        ),
    ]
