# Generated by Django 5.2.17 on 2026-09-20 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_documentstructureindex_documentstructurechunk_and_more'),
        ('experiments', '0002_project_visibility'),
        ('materials', '0007_structure_index'),
        ('papers', '0006_paperreadingstate_readingreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(choices=[('material', 'material'), ('paper', 'paper'), ('document', 'document'), ('experiment_project', 'experiment_project'), ('experiment_run', 'experiment_run')], max_length=24)),
                ('title', models.CharField(max_length=500)),
                ('ownership_state', models.CharField(max_length=20)),
                ('policy_origin', models.CharField(default='legacy_adapter', max_length=20)),
                ('observation_sha256', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('operation_key', models.CharField(max_length=120)),
                ('payload_kind', models.CharField(max_length=24)),
                ('snapshot', models.JSONField(null=True)),
                ('schema_version', models.CharField(default='registry-v1', max_length=32)),
                ('canonicalization_version', models.CharField(default='json-sorted-utf8-v1', max_length=32)),
                ('file_sha256', models.CharField(max_length=64, null=True)),
                ('content_sha256', models.CharField(max_length=64, null=True)),
                ('metadata_sha256', models.CharField(max_length=64)),
                ('observation_sha256', models.CharField(max_length=64)),
                ('source_kind', models.CharField(max_length=40)),
                ('generator_kind', models.CharField(default='system', max_length=16)),
                ('generator_name', models.CharField(default='registry_adapter', max_length=32)),
                ('generator_version', models.CharField(default='1', max_length=16)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='documents.documentversion')),
                ('material_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='materials.materialversion')),
                ('research_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='registry.researchobject')),
                ('source_revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='registry.researchrevision')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchObjectBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='documents.document')),
                ('experiment_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='experiments.experimentproject')),
                ('experiment_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='experiments.experimentrun')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='materials.material')),
                ('paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='papers.paper')),
                ('research_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='binding', to='registry.researchobject')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('pk__isnull', True), ('pk__isnull', False)), models.Q(('material_id__isnull', False), ('paper_id__isnull', True), ('document_id__isnull', True), ('experiment_project_id__isnull', True), ('experiment_run_id__isnull', True)), models.Q(('material_id__isnull', True), ('paper_id__isnull', False), ('document_id__isnull', True), ('experiment_project_id__isnull', True), ('experiment_run_id__isnull', True)), models.Q(('material_id__isnull', True), ('paper_id__isnull', True), ('document_id__isnull', False), ('experiment_project_id__isnull', True), ('experiment_run_id__isnull', True)), models.Q(('material_id__isnull', True), ('paper_id__isnull', True), ('document_id__isnull', True), ('experiment_project_id__isnull', False), ('experiment_run_id__isnull', True)), models.Q(('material_id__isnull', True), ('paper_id__isnull', True), ('document_id__isnull', True), ('experiment_project_id__isnull', True), ('experiment_run_id__isnull', False)), _connector='OR'), name='registry_binding_exactly_one'), models.UniqueConstraint(condition=models.Q(('material__isnull', False)), fields=('material',), name='registry_bind_material'), models.UniqueConstraint(condition=models.Q(('paper__isnull', False)), fields=('paper',), name='registry_bind_paper'), models.UniqueConstraint(condition=models.Q(('document__isnull', False)), fields=('document',), name='registry_bind_document'), models.UniqueConstraint(condition=models.Q(('experiment_project__isnull', False)), fields=('experiment_project',), name='registry_bind_experiment_project'), models.UniqueConstraint(condition=models.Q(('experiment_run__isnull', False)), fields=('experiment_run',), name='registry_bind_experiment_run')],
            },
        ),
        migrations.AddField(
            model_name='researchobject',
            name='current_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='registry.researchrevision'),
        ),
        migrations.AddConstraint(
            model_name='researchrevision',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='registry_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='researchrevision',
            constraint=models.UniqueConstraint(fields=('research_object', 'number'), name='registry_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='researchrevision',
            constraint=models.UniqueConstraint(fields=('research_object', 'operation_key'), name='registry_operation_once'),
        ),
        migrations.AddConstraint(
            model_name='researchrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document_version__isnull', True), ('material_version__isnull', False), ('payload_kind', 'material_version'), ('snapshot__isnull', True)), models.Q(('document_version__isnull', False), ('material_version__isnull', True), ('payload_kind', 'document_version'), ('snapshot__isnull', True)), models.Q(('document_version__isnull', True), ('material_version__isnull', True), ('payload_kind', 'baseline_snapshot'), ('snapshot__isnull', False)), _connector='OR'), name='registry_revision_payload'),
        ),
        migrations.AddConstraint(
            model_name='researchrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('material_version__isnull', False)), fields=('material_version',), name='registry_material_version_once'),
        ),
        migrations.AddConstraint(
            model_name='researchrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('document_version__isnull', False)), fields=('document_version',), name='registry_document_version_once'),
        ),
        migrations.AddConstraint(
            model_name='researchobject',
            constraint=models.CheckConstraint(condition=models.Q(('object_type__in', ('material', 'paper', 'document', 'experiment_project', 'experiment_run'))), name='registry_object_type'),
        ),
        migrations.AddConstraint(
            model_name='researchobject',
            constraint=models.CheckConstraint(condition=models.Q(('ownership_state__in', ('known', 'unresolved', 'team_custody'))), name='registry_ownership_state'),
        ),
        migrations.AddConstraint(
            model_name='researchobject',
            constraint=models.CheckConstraint(condition=models.Q(('policy_origin', 'legacy_adapter')), name='registry_legacy_policy'),
        ),
    ]
