# Generated by Django 5.2.14 on 2026-09-15 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_material_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_version', models.CharField(max_length=80)),
                ('source_sha256', models.CharField(max_length=64)),
                ('is_current', models.BooleanField(default=False)),
                ('sections', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_indexes', to='materials.materialversion')),
            ],
        ),
        migrations.CreateModel(
            name='StructureChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('section', models.PositiveIntegerField(default=0)),
                ('title_path', models.TextField(blank=True)),
                ('text', models.TextField()),
                ('line_start', models.PositiveIntegerField()),
                ('line_end', models.PositiveIntegerField()),
                ('evidence_ids', models.JSONField(default=list)),
                ('oversized', models.BooleanField(default=False)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='materials.structureindex')),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
        migrations.AddConstraint(
            model_name='structureindex',
            constraint=models.UniqueConstraint(fields=('version', 'parser_version', 'source_sha256'), name='structure_generation_unique'),
        ),
        migrations.AddConstraint(
            model_name='structureindex',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('version',), name='structure_current_unique'),
        ),
        migrations.AddConstraint(
            model_name='structurechunk',
            constraint=models.UniqueConstraint(fields=('index', 'ordinal'), name='structure_chunk_ordinal'),
        ),
    ]
