# Generated by Django 5.2.14 on 2026-09-15 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_imports'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStructureIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_version', models.CharField(max_length=80)),
                ('source_sha256', models.CharField(max_length=64)),
                ('is_current', models.BooleanField(default=False)),
                ('sections', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_indexes', to='documents.documentversion')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentStructureChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('section', models.PositiveIntegerField(default=0)),
                ('title_path', models.TextField(blank=True)),
                ('text', models.TextField()),
                ('line_start', models.PositiveIntegerField()),
                ('line_end', models.PositiveIntegerField()),
                ('oversized', models.BooleanField(default=False)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.documentstructureindex')),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentstructureindex',
            constraint=models.UniqueConstraint(fields=('version', 'parser_version', 'source_sha256'), name='doc_structure_generation_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentstructureindex',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('version',), name='doc_structure_current_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentstructurechunk',
            constraint=models.UniqueConstraint(fields=('index', 'ordinal'), name='doc_structure_chunk_ordinal'),
        ),
    ]
