# Generated by Django 5.2.14 on 2026-05-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_enable_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('paper', 'Paper'), ('document', 'Document'), ('experiment', 'Experiment')], max_length=32)),
                ('object_id', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('space_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('keywords_json', models.JSONField(blank=True, default=list)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['object_type', 'title'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='search_sear_object__1fac01_idx'), models.Index(fields=['space_id'], name='search_sear_space_i_36a1b0_idx')],
                'unique_together': {('object_type', 'object_id')},
            },
        ),
    ]
