# Generated by Django 5.2.14 on 2026-05-25 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionMapSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('nodes_json', models.JSONField(blank=True, default=list)),
                ('edges_json', models.JSONField(blank=True, default=list)),
                ('generator', models.CharField(default='manual_v1', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('root_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_map_snapshots', to='library.knowledgespace')),
            ],
            options={
                'ordering': ['-version', '-id'],
                'unique_together': {('root_space', 'version')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSpaceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('related', 'Related'), ('prerequisite', 'Prerequisite'), ('extends', 'Extends'), ('competes', 'Competes'), ('application', 'Application')], default='related', max_length=32)),
                ('weight', models.FloatField(default=1.0)),
                ('evidence_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='library.knowledgespace')),
                ('target_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='library.knowledgespace')),
            ],
            options={
                'ordering': ['source_space_id', 'target_space_id'],
                'unique_together': {('source_space', 'target_space', 'relation_type')},
            },
        ),
    ]
